kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testupdated-oct4-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: testupdated-oct4-dsp-job
    namespace: rhdh-newapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testupdated-oct4-dsp-job-role